# General Jekyll Config
highlighter: pygments
url: http://bellicano.it
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]



# Links to include in top navigation
# For external links add external: true
#links:
#  - title: Home
#    url: /
#  - title: About
#    url: /about
#  - title: Resources
#    url: /resources
#  - title: Notes
#    url: /notes

#links:
#  - { title: Home, url: /index }
#  - { title: About, url: /about }
#  - { title: Resources, url: /resources }
#  - { title: Notes, url: /notes }
